[project]
authors = ["Hannah Zafar <hannah.zafar@nasa.gov>"]
channels = ["conda-forge"]
description = "Comparative analysis between FLUXNET observations and Land Carbon Models"
name = "FLUXNET-Model-comparison"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.3.1,<3"
matplotlib = ">=3.10.3,<4"
pandas = ">=2.3.1,<3"
xarray = ">=2025.7.1,<2026"
h5netcdf = ">=1.6.3,<2"
ipykernel = ">=6.29.5,<7"
cartopy = ">=0.24.0,<0.25"
dask = ">=2025.7.0,<2026"
timezonefinder = ">=6.5.9,<7"
scikit-learn = ">=1.7.1,<2"
pip = ">=25.2,<26"

[pypi-dependencies]
merra2-tools = { git = "https://github.com/hannahzafar/merra2-tools.git", tag = "v0.2.0"}
